dist: xenial
language: python
matrix:
  include:
    - python: 3.7
      env: TOXENV=py37
    - python: 3.6
      env:
        - TOXENV=py36
        - TOXENV=flake8
    - python: 3.5
      env: TOXENV=py35
    - python: 3.4
      env: TOXENV=py34
    - python: 2.7
      env: TOXENV=py27
before_install: sudo apt-get install -y ffmpeg
install: pip install tox
script: tox
