language: python
services:
  - docker
matrix:
  include:
    - env:
      - TOXENV=py37
      - DOCKER_IMAGE=python:3.7
    - env:
      - TOXENV=py36,flake8
      - DOCKER_IMAGE=python:3.6
    - env:
      - TOXENV=py35
      - DOCKER_IMAGE=python:3.5
    - env:
      - TOXENV=py27
      - DOCKER_IMAGE=python:2.7
before_install:
  - docker pull $DOCKER_IMAGE
script: docker run -e "TOXENV=$TOXENV" -v "$(pwd):/usr/src/app" $DOCKER_IMAGE python setup.py test
