language: python
services:
  - docker
matrix:
  include:
    - env: TOXENV=py37
    - env: TOXENV=py36,flake8
    - env: TOXENV=py35
    - env: TOXENV=py27
before_install:
  - docker pull ggueret/pelican-dashify
script: docker run -e "TOXENV=$TOXENV" -v "$(pwd):/usr/src/app" ggueret/pelican-dashify
